#!/bin/bash

set -e

rm -Rf "./ci-build"
mkdir "./ci-build"
cd "./ci-build"

${CHERRY_LIB_MESONSETUP} \
        --cross-file "${CHERRY_LIB_SRCDIR}/src/x86_64-unknown-uefi.mesoncross.ini" \
        . \
        "${CHERRY_LIB_SRCDIR}"
${CHERRY_LIB_NINJABUILD}
${CHERRY_LIB_MESONTEST}
